version: "3"
services:
  api:
    build: .
    container_name: api
    command: npm run start
    expose:
      - "3000"
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      NODE_ENV: "development"
    volumes:
      - ./api:/api
